sudo: required
dist: trusty
language: node_js
node_js:
  - node

before_script:
  - npm install

script:
  - npm run build
  - npm version patch

before_deploy:
  - npm run packagr
  - cd dist

deploy:
  provider: npm
  email: "tumit@live.com"
  skip_cleanup: true
  api_key: $NPM_TOKEN

notifications:
  email: # only receive email when the build status changes (someone broke the build!)
    on_failure: change
    on_success: change
